
spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    data:
        mongodb:
            uri: mongodb://localhost:27017
            database: farmService
    mail:
        host: localhost
        port: 25
        username:
        password:
    thymeleaf:
        cache: true
    zipkin:
        base-url: http://localhost:9411
        enabled: false
        locator:
            discovery:
                enabled: true


server:
    port: 8081
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024


application:
    http:
        version: V_1_1
        cache:
            timeToLiveInDays: 1461
    security:
        authentication:
            jwt:
                secret: 7c2f4aa1973e8787aa75950251653c85f7e91538
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail:
        from: farmService@localhost
        base-url: http://my-server-url-to-change
    metrics:
        jmx.enabled: true
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: farmService
        prometheus:
            enabled: false
            endpoint: /prometheusMetrics
        logs:
            enabled: false
            report-frequency: 60
    logging:
        logstash:
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512
        spectator-metrics:
            enabled: false
